from .title_slide import TitleSlide
from .diffusion_intro_slide import DiffusionIntroSlide
from .process_overview_slide import ProcessOverviewSlide
from .forward_diffusion_slide import ForwardDiffusionSlide
from .reverse_denoising_slide import ReverseDenoisingSlide
from .celebahq_demo_slide import CelebAHQDemoSlide
from .ddpm_innovation_slide import DDPMInnovationSlide
